### ISSUE TITLE
REQUEST:  Provide option to obtain kext from a direct URL link 

### ISSUE THREAD

**Issue by steveschow** [axivo/opencore#55]
some commonly used KEXT come from direct link on the net rather then from GitHub, for example RadeonBoost (far as I know, and its even zipped too).  Please provide options to grab kext from these other kinds of sources when not provided by GitHub.  This could also be applicable for the dual processor kext, which some people don't need or want installed.

**Comment by fmunteanu** [comment]
You can place any properly named zipped kext into `/files` directory and the generator will install it. The mandatory `AppleMCEReporterDisabler.kext` is installed only when a dual processor setup is detected. You are repeating the same query into several issues.

**Comment by steveschow** [comment]
I have moved on to using my own simple scripts to get the job done a better way.  Good luck with this project
