### ISSUE TITLE
REQUEST: Need way to add kernel entries without kext

### ISSUE THREAD

**Issue by steveschow** [axivo/opencore#56]
If I am using this tool just to edit the config.plist and NOT to automatically download kext files, etc.. then I need a way to add entries to the Kernel area without knowing ahead of time the item #'s to use.  I do not see how this is possible now because I will not know in advance which item# to use for each one since that might change with a new base config.plist from cdf

**Comment by steveschow** [comment]
might be able to just assume for now that CDF's kernel area will always be blank to start out.

**Comment by steveschow** [comment]
also since your script is by default adding the dual processor kext, then I don't know what item #'s to use for my config.plist patching.

**Comment by fmunteanu** [comment]
The plist generator adds the mandatory `AppleMCEReporterDisabler.kext` only when it detects a dual processor setup. You can set any kernel configuration in your `setup.py`.

**Comment by steveschow** [comment]
I've moved on to using my own scripts as a better solution, this solution is too strictly confined to one way of doing things.  Good luck with the project.
