### ISSUE TITLE
REQUEST config.plist-only mode

### ISSUE THREAD

**Issue by steveschow** [axivo/opencore#58]
This script is mainly useful to editing the config.plist, but it implicity does a lot of other stuff, in the name of being automatic, but all that stuff is not of use to me.  I prefer to download OC myself and setup the dirs and kexts, and basically just use this script to modify the config.plist...can there be a mode that only does that?

**Comment by fmunteanu** [comment]
Yes, you can run only the config build. It will look for additional kexts into `/files` directory and if not found, it will check if your machine is a dual process and install the mandatory `AppleMCEReporterDisabler.kext`. See the wiki for details.

Example of a config build:

```python
#!/usr/bin/env python

from opencore.build import OpenCoreBuild


if __name__ == '__main__':
    kexts = []
    build = OpenCoreBuild('Volumes/EFI', kexts)
    settings = {}
    build.write_plist(settings)
```

**Comment by steveschow** [comment]
I've moved on to a better solution using my own scripts.  Good luck with this project
