### ISSUE TITLE
config.plist not created

### ISSUE THREAD

**Issue by steveschow** [axivo/opencore#59]
I attempted to run the script per the instructions, but no config.plist was created anywhere.

**Comment by startergo** [comment]
Just tested it and it works fine cloned repo is in:

```
~Downloads/opencore/
```

And the config location is:

```
~Downloads/opencore/Volumes/EFI/EFI/OC/config.plist
```

**Comment by steveschow** [comment]
do you have any ideas why it is not working for me?  It creates /EFI/EFI/OC and copies in the kext's, drivers, etc.. but no config.plist ever gets created there.

**Comment by startergo** [comment]
Which python? Install latest python from their website.

**Comment by steveschow** [comment]
python 2.7.16.  Not an option to change that.

**Comment by steveschow** [comment]
I think I figured it out.  The error messaging is not great.  this is message in console while running it:

```
Traceback (most recent call last):
  File "mysetup.py", line 97, in <module>
    build.write_plist(settings)
  File "/Users/sjs/Development/github/opencore/opencore/build.py", line 482, in write_plist
    self.update_settings(self.settings, settings)
  File "/Users/sjs/Development/github/opencore/opencore/build.py", line 467, in update_settings
    result[key] = self.update_settings(result.get(key, {}), value)
  File "/Users/sjs/Development/github/opencore/opencore/build.py", line 467, in update_settings
    result[key] = self.update_settings(result.get(key, {}), value)
  File "/Users/sjs/Development/github/opencore/opencore/build.py", line 467, in update_settings
    result[key] = self.update_settings(result.get(key, {}), value)
AttributeError: 'list' object has no attribute 'get'
```

I looked at my settings={} section and figured out I was trying to specify Kernel add entries wrongly, not as a proper array, which I figured out and it works.
