### ISSUE TITLE
Wiki page clarification

### ISSUE THREAD

**Issue by startergo** [axivo/opencore#71]
It is not very clear in the example:
https://github.com/axivo/opencore/wiki/Configuration%3A-Big-Sur
Where to place methods and how to use them:
```
__init__
configure_kexts
copy_tree
extract_files
install_kext
install_opencore
print_bold
update_settings
```

Please provide an example file.

**Comment by fmunteanu** [comment]
@startergo these are internal methods used for `OpenCoreBuild` class to automate the creation of EFI tree and `config.plist` file. The only methods you will use as end-user are `write_tree()`, `write_plist()` and `run_misc_tasks()`.

In fact an end-user will be concerned only about the custom settings, in other words the `kexts` and `settings` variables.
